apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  serviceAccountName: redis-enterprise-operator
  containers:
    - name: app
      image: rezarahim/alpine-tools:1.1
      command:
        - "/bin/sh"
        - "-c"
        - |
          sleep 3600
      volumeMounts:
        - name: config-volume-acl
          mountPath: /etc/config/acl/
          readOnly: true
        - name: config-volume-rec
          mountPath: /etc/config/rec/
          readOnly: true
        - name: config-volume-remote-cluster
          mountPath: /etc/config/remote/
          readOnly: true    
      env:
        - name: REC_USERNAME
          valueFrom:
            secretKeyRef:
              name: ${RECNAME}
              key: username
        - name: REC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${RECNAME}
              key: password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: HEATHCHECK_USERNAME
          valueFrom:
            secretKeyRef:
              name: health-check-user
              key: username
        - name: HEATHCHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: health-check-user
              key: password
  volumes:
    - name: config-volume-acl
      configMap:
        name: config-map-acl
    - name: config-volume-rec
      configMap:
        name: config-map-rec
    - name: config-volume-remote-cluster
      configMap:
        name: config-map-remote-cluster
