apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db1
spec:
  memorySize: {{ .Values.memorySize }}
  databasePort: {{ .Values.databasePort }}
  shardCount: {{ .Values.shardCount }}
  replication: true
  tlsMode: enabled
  rolesPermissions:
    - role: "health-check-role"
      acl: "health-check-acl"
      type: "redis-enterprise"
    - role: "full-access-role"
      acl: "Full Access"
      type: "redis-enterprise"
