s3RecBucket: redis-argocd-bank/dev
clusterName: south
env: dev
recname: south-dev-rec
namespace: south-dev

nodes: 3

redisEnterpriseImageSpec: redislabs/redis
redisEnterpriseServicesRiggerImageSpec: redislabs/k8s-controller
bootstrapperImageSpec: redislabs/operator
versionTag: 7.8.4-95

limits:
    cpu: "2000m"
    memory: "4000Mi"
requests:
    cpu: "2000m"
    memory: "4000Mi"

storageClass: "standard"
volumeSize: "8000Mi"

#south cluster
apiFqdnUrl: api.south.ps-redis.com
dbFqdnSuffix: -cluster.south.ps-redis.com

method: ingress
ingressClass: nginx 
username: test@example.com
