apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-acl
data:
  config-map-acl.sh: |
    # Create an ACL for key prefix abc
    curl -k -u "$REC_USERNAME:$REC_PASSWORD" -X POST \
      -H 'Content-Type: application/json' \
      -d '{ "name": "health-check-acl", "acl": "~xxxxxxx* +get" }' \
      https://{{ .Values.recname }}:9443/v1/redis_acls

    # Create abc-role role_uids=2
    curl -k -u "$REC_USERNAME:$REC_PASSWORD" -X POST \
      -H 'Content-Type: application/json' \
      -d '{"management":"none","name":"health-check-role"}' \
      https://{{ .Values.recname }}:9443/v1/roles

    #   
    curl -k -u "$REC_USERNAME:$REC_PASSWORD" -X POST \
      -H 'Content-Type: application/json' \
      -d '{"management":"none","name":"full-access-role"}' \
      https://{{ .Values.recname }}:9443/v1/roles  

    # Create user
    curl -k -u "$REC_USERNAME:$REC_PASSWORD" -X POST \
    -H 'Content-Type: application/json' \
    -d "{\"email\": \"health-check-user@example.com\", \"password\": \"$HEATHCHECK_PASSWORD\", \"name\": \"$HEATHCHECK_USERNAME\", \"role_uids\": [2], \"auth_method\": \"regular\"}" \
    "https://{{ .Values.recname }}:9443/v1/users"

    # Encrypt the password and encode with base64
    #echo "password" | openssl pkeyutl  -encrypt -inkey public_key.pem -pubin  | base64 
    
    export ENCRYPTED_PASSWORD="bJd6H3hk8xfhTp5MCzxoH6GVw06ubUqTlsNdjxX8ExoasrwmQLYwuDcnAXPE7x4zC3Uwp3w3/OvhdJwIwL1rJ9RPh2K6/QzieXW6cRaYmyUD4uw3+Fcw56mG8+loiEbeWurITBJPt/YIGS5COUBoZq7yU+9ILHEh7wDqhDvYFarFymjASHT3Ml73326kJcl+TiqtEWgZ0QBPoOtZlYzS2ISutdD4ryymmE3mi4BQZJ38MSsIsdZ6ju1ZilkFXNmiZnx2EL2qvuPz91vBnbzwuHernU4O2OtdL4HFVhcvqf7mEF2K+Xq0E3lHJuWkAsZFPe9AHB/vrqbG4abzvKeBjg=="

    export USER_PASSWORD=$(echo "$ENCRYPTED_PASSWORD" | base64 -d | openssl pkeyutl -decrypt -inkey /tmp/private_key.pem)
    
    read -r -d '' payload <<EOF
    {
      "export_location":{
        "email": "user@example.com",
        "password": "$USER_PASSWORD",
        "name": "user",
        "role_uids": [3],
        "auth_method": "regular"
      } 
    }
    EOF

    curl -k -u "$REC_USERNAME:$REC_PASSWORD" -X POST \
     -H "Content-Type: application/json" \
     -d "$payload" \
     "https://{{ .Values.recname }}:9443/v1/users"

