apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-rec
data:
  config-map-rec.sh: |
     
     export S3_BUCKET={{ .Values.s3RecBucket  }}
     export CLUSTER_NAME={{ .Values.clusterName  }}
     export ENVIRONMENT={{ .Values.environment  }}
     export REC_NAME={{ .Values.recname }}

     kubectl get secret rsa-keys -n south-dev -o jsonpath="{.data.public_key\.pem}" | base64 -d > /tmp/public_key.pem
     kubectl get secret rsa-keys -n south-dev -o jsonpath="{.data.private_key\.pem}" | base64 -d > /tmp/private_key.pem
     
     aws s3 cp s3://$S3_BUCKET/cluster_config.json /tmp/cluster_config.json

     jq -c '.[]' /tmp/cluster_config.json | while read -r item; do
       eval $(echo "$item" | jq -r 'to_entries|map("\(.key)=\(.value|@sh)")|.[]')
  
       if [ "$clusername" = "$CLUSTER_NAME" ]; then
       # Example usage:
         echo "clusername: $clusername, s3_dir: $s3_dir, primary: $primary"
         echo $REC_USERNAME | openssl pkeyutl  -encrypt -inkey /tmp/public_key.pem -pubin  -out /tmp/username.bin
         echo $REC_PASSWORD | openssl pkeyutl  -encrypt -inkey /tmp/public_key.pem -pubin  -out /tmp/passwd.bin

         aws s3 cp /tmp/username.bin s3://$S3_BUCKET/$s3_dir/
         aws s3 cp /tmp/passwd.bin s3://$S3_BUCKET/$s3_dir/
          if [ "$primary" = "false" ]; then
             exit
          fi
       fi
     done

     #it's primary cluster
     while true; do
        all_found=true

        # Loop over each cluster item in the JSON
        while IFS= read -r item; do
           eval $(echo "$item" | jq -r 'to_entries | map("\(.key)=\(.value|@sh)") | .[]')

           echo "Checking: s3://$S3_BUCKET/$s3_dir/username.bin"

           if ! aws s3 ls "s3://$S3_BUCKET/$s3_dir/username.bin" > /dev/null 2>&1; then
              echo "Not found: $s3_dir/username.bin"
              all_found=false
           else
             echo " Found: $s3_dir/username.bin"
           fi
        done < <(jq -c '.[]' cluster_config.json)

        # Exit only if all files were found
        if [ "$all_found" = true ]; then
          echo "All required S3 files are present!"
          break
        fi
     done
     
  echo " Some files not ready yet, retrying in 5 seconds..."
  sleep 30
done
      

     

