---
apiVersion: v1
kind: Service
metadata:
  name: health-check
spec:
  selector:
    app: health-check
  ports:
    - name: http
      port: 5000         # Port exposed inside the cluster
      targetPort: 5000   # Port exposed by the container
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check
    spec:
      serviceAccountName: redis-enterprise-operator
      containers:
        - name: webapp
          image: rezarahim/alpine-tool:1.2
          command:
            - "/bin/sh"
            - "-c"
            - |
              python /etc/config/health/app.py
          env:
            - name: HEATHCHECK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: health-check-user
                  key: username
            - name: HEATHCHECK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: health-check-user
                  key: password
          volumeMounts:
            - name: flask-app-code
              mountPath: /etc/config/health
      volumes:
        - name: flask-app-code
          configMap:
            name: flask-redis-app
